controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home_index: path: /
  controller: App\Controller\FigureController::index
  methods: [GET]

home_add:
  path: /ajout
  controller: App\Controller\FigureController::addFig
  methods: [GET|POST]

home_details:
  path: /{slug}
  controller: App\Controller\FigureController::detail
  methods: [GET|POST]

home_delete:
  path: /{slug}/supprimer
  controller: App\Controller\FigureController::deleteFig
  methods: [GET]

home_edit:
  path: /{slug}/edit
  controller: App\Controller\FigureController::editFig
  methods: [GET|POST]

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: [GET, POST]

app_verify:
  path: /verify/{token}
  controller: App\Controller\RegistrationController::verify
  methods: [GET]

app_resend:
  path: /resend
  controller: App\Controller\RegistrationController::resend
  methods: [GET]

image_delete:
    path: /image/delete/{id}
    methods: [DELETE]
    controller: App\Controller\ImageController::deleteImage

videos_delete:
    path: /videos/delete/{id}
    methods: [DELETE]
    controller: App\Controller\VideosController::deleteVideos

app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [GET]

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
  methods: [GET]

app_forgot:
  path: /forgot
  controller: App\Controller\SecurityController::forgotPassword
  methods: [GET, POST]

app_reset:
  path: /reset/{token}
  controller: App\Controller\SecurityController::resetPassword
  methods: [GET, POST]
